#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banco_de_Dados.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_ARS")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttb_carta(tb_carta instance);
    partial void Updatetb_carta(tb_carta instance);
    partial void Deletetb_carta(tb_carta instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Banco_de_Dados.DAL.Properties.Settings.Default.db_ARSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_carta> tb_cartas
		{
			get
			{
				return this.GetTable<tb_carta>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_carta")]
	public partial class tb_carta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cartorio;
		
		private string _protocolo;
		
		private string _dataprotocolo;
		
		private string _destinatario;
		
		private string _docdestinatario;
		
		private string _endereco;
		
		private string _complemento;
		
		private string _bairro;
		
		private string _cidade;
		
		private string _UF;
		
		private string _CEP;
		
		private string _nrointimacao;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncartorioChanging(string value);
    partial void OncartorioChanged();
    partial void OnprotocoloChanging(string value);
    partial void OnprotocoloChanged();
    partial void OndataprotocoloChanging(string value);
    partial void OndataprotocoloChanged();
    partial void OndestinatarioChanging(string value);
    partial void OndestinatarioChanged();
    partial void OndocdestinatarioChanging(string value);
    partial void OndocdestinatarioChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OncomplementoChanging(string value);
    partial void OncomplementoChanged();
    partial void OnbairroChanging(string value);
    partial void OnbairroChanged();
    partial void OncidadeChanging(string value);
    partial void OncidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnCEPChanging(string value);
    partial void OnCEPChanged();
    partial void OnnrointimacaoChanging(string value);
    partial void OnnrointimacaoChanged();
    #endregion
		
		public tb_carta()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cartorio", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string cartorio
		{
			get
			{
				return this._cartorio;
			}
			set
			{
				if ((this._cartorio != value))
				{
					this.OncartorioChanging(value);
					this.SendPropertyChanging();
					this._cartorio = value;
					this.SendPropertyChanged("cartorio");
					this.OncartorioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_protocolo", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string protocolo
		{
			get
			{
				return this._protocolo;
			}
			set
			{
				if ((this._protocolo != value))
				{
					this.OnprotocoloChanging(value);
					this.SendPropertyChanging();
					this._protocolo = value;
					this.SendPropertyChanged("protocolo");
					this.OnprotocoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dataprotocolo", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string dataprotocolo
		{
			get
			{
				return this._dataprotocolo;
			}
			set
			{
				if ((this._dataprotocolo != value))
				{
					this.OndataprotocoloChanging(value);
					this.SendPropertyChanging();
					this._dataprotocolo = value;
					this.SendPropertyChanged("dataprotocolo");
					this.OndataprotocoloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destinatario", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string destinatario
		{
			get
			{
				return this._destinatario;
			}
			set
			{
				if ((this._destinatario != value))
				{
					this.OndestinatarioChanging(value);
					this.SendPropertyChanging();
					this._destinatario = value;
					this.SendPropertyChanged("destinatario");
					this.OndestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_docdestinatario", DbType="NVarChar(13) NOT NULL", CanBeNull=false)]
		public string docdestinatario
		{
			get
			{
				return this._docdestinatario;
			}
			set
			{
				if ((this._docdestinatario != value))
				{
					this.OndocdestinatarioChanging(value);
					this.SendPropertyChanging();
					this._docdestinatario = value;
					this.SendPropertyChanged("docdestinatario");
					this.OndocdestinatarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_complemento", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string complemento
		{
			get
			{
				return this._complemento;
			}
			set
			{
				if ((this._complemento != value))
				{
					this.OncomplementoChanging(value);
					this.SendPropertyChanging();
					this._complemento = value;
					this.SendPropertyChanged("complemento");
					this.OncomplementoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bairro", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string bairro
		{
			get
			{
				return this._bairro;
			}
			set
			{
				if ((this._bairro != value))
				{
					this.OnbairroChanging(value);
					this.SendPropertyChanging();
					this._bairro = value;
					this.SendPropertyChanged("bairro");
					this.OnbairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cidade", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string cidade
		{
			get
			{
				return this._cidade;
			}
			set
			{
				if ((this._cidade != value))
				{
					this.OncidadeChanging(value);
					this.SendPropertyChanging();
					this._cidade = value;
					this.SendPropertyChanged("cidade");
					this.OncidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEP", DbType="NVarChar(8) NOT NULL", CanBeNull=false)]
		public string CEP
		{
			get
			{
				return this._CEP;
			}
			set
			{
				if ((this._CEP != value))
				{
					this.OnCEPChanging(value);
					this.SendPropertyChanging();
					this._CEP = value;
					this.SendPropertyChanged("CEP");
					this.OnCEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nrointimacao", DbType="NVarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nrointimacao
		{
			get
			{
				return this._nrointimacao;
			}
			set
			{
				if ((this._nrointimacao != value))
				{
					this.OnnrointimacaoChanging(value);
					this.SendPropertyChanging();
					this._nrointimacao = value;
					this.SendPropertyChanged("nrointimacao");
					this.OnnrointimacaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
